### ISSUE TITLE
Neoscopes not loading

### ISSUE THREAD

**Issue by DaitiDay** [smartpde/neoscopes#1]
I tried to install the package through packer. Everything seems to be installed correctly but when I try to use one of the plugin function I get a `error loading module`. Using a protected call for the plugin, printing "No neoscope" if the loading fails, I can actually confirm the plugin is not loaded.

**Comment by defr0std** [comment]
Sorry for delay, forgot to set up a watch on the repository :)
Could you please share how you are loading the plugin? Are you requiring neoscope or neoscope**s** (the second one is correct).

**Comment by DaitiDay** [comment]
I'm loading the plugin this way:
```
local ns_status_ok, ns = pcall(require, "neoscopes")
if not ns_status_ok then
    print('No neoscopes')
  return
end
```
After opening a file, or just launching nvim, is I inspect the `:messages` I can see the _No neoscopes_ printed (and therefore neoscopes setup/keybinds do not work)

**Comment by defr0std** [comment]
Ah, ok. Could you please try updating the plugin? I have pushed another fix yesterday which may actually fix this issue as well.

**Comment by DaitiDay** [comment]
I'm not at home at the moment, I'll try to update as soon as I get back home in like 2 hours or so

**Comment by DaitiDay** [comment]
Sorry for being late, finishing my work took longer than expected. I've updated and now the plugins seems to be loaded. I'll do some tests and, if that's the case, I'll close this issue. Thank you 😄

**Comment by defr0std** [comment]
Absolutely no worries at all, thank you for reporting it and sorry for the troubles.
