### ISSUE TITLE
startup_scope fails when passing a file as argument to nvim

### ISSUE THREAD

**Issue by moinmoti** [smartpde/neoscopes#2]
The plugin mostly works as expected, but returns the following error on opening neovim with a file. Afterwards, `<startup>` is absent from select scopes window.
```
packer.nvim: Error running config for neoscopes: .../nvim/site/pack/packer/start/neoscopes/lua/neoscopes.lua:75: attempt to index upvalue 'utils' (a boolean value)
```

PS – Thanks for the plugin, the fact that it works so smoothly with auto-sessions plugin is a boon.

**Comment by defr0std** [comment]
Whoops, forgot to git add a file, which coincidentally still exists in my dots :)
