### ISSUE TITLE
Duplicate entry in find_files window

### ISSUE THREAD

**Issue by moinmoti** [smartpde/neoscopes#3]
Setting – I have `~/.config/nvim` added to all scopes. Now I am in `~/.config/nvim`, and I open `init.lua` by executing 
``` bash
nvim init.lua
```

Bug – `find_files` shows duplicate entry for `init.lua`.

**Comment by moinmoti** [comment]
Yes, I have integrated Telescope like specified in the readme. I have the default telescope setup, and following is my neoscopes setup:

``` lua
local scopes = require 'neoscopes'

-- Helper functions to fetch the current scope and set `search_dirs`
_G.find_files = function()
  require('telescope.builtin').find_files({
    search_dirs = scopes.get_current_dirs()
  })
end
_G.live_grep = function()
  require('telescope.builtin').live_grep({
    search_dirs = scopes.get_current_dirs()
  })
end

scopes.add_startup_scope()
```

**Comment by defr0std** [comment]
Thanks for the full repro! This issue should be fixed now, if you update the plugin.
