### ISSUE TITLE
Way to query if any scope is set

### ISSUE THREAD

**Issue by jeanlucthumm** [smartpde/neoscopes#8]
Consider changing the API of this:

https://github.com/smartpde/neoscopes/blob/2654f275bf3fb3d3a255b7925464d4cade5b9083/lua/neoscopes.lua#L241

To return nil instead of error when there is no scope set. Otherwise, there's no way to tell safely whether `set_current` has been called at least once.

**Comment by defr0std** [comment]
Sure, that makes sense, thanks!
